In [26]:
import numpy as np
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import precision_score, recall_score, f1_score
actual = [1, 1] 
predicted = [1, 0] 

In [12]:
results = confusion_matrix(actual, predicted)

In [13]:
print(results)

[[0 0]
 [1 1]]


In [15]:
y_actual = ["cat", "ant", "cat", "cat", "ant"]
y_pred = ["ant", "ant", "cat", "cat", "ant"]
confusion_matrix(y_actual, y_pred, labels=["ant","cat"])

array([[2, 0],
       [1, 2]], dtype=int64)

In [21]:
actual = [1, 1, 0, 1, 0, 0, 1, 0, 0, 0] 
predicted = [1, 0, 0, 1, 0, 0, 1, 1, 1, 0] 
result=confusion_matrix(actual, predicted)
print(result)

[[4 2]
 [1 3]]


In [22]:
precision_score(actual,predicted)

0.6

In [23]:
recall_score(actual,predicted)

0.75

In [27]:
f1_score(actual,predicted)

0.6666666666666666